### PR TITLE
Label rectangles with letters instead of numbers

### PR DESCRIPTION
**Pull request by nmay231**
This is just a suggestion to make the presentation of the problem a little clearer.

I was momentarily confused with the two sets of numbers in the image of the puzzle description. It would be easier to understand if the rectangles were labeled with letters `A-K` instead of numbers `0-10`. However, that requires updating the image /:

[Example](https://imgur.com/9pAQnpt) updated image (of amazing quality :wink: ).

If you don't feel it's worth the effort, I getcha.

Cheers! (cool puzzle, by the way)

### CODE REVIEW

**Comment by Philippe-Cholet** [comment]
Well I could (the image was made from svg which is totally editable) but I thought a different color would be enough to distinguish them, and I still think that.
Right now to quote you, I don't feel it's worth the effort. but if it bothers other people, I will change it.
Glad you liked it, by the way!

**Comment by Philippe-Cholet** [comment]
Well I'm changing it.

**Comment by Philippe-Cholet** [comment]
I added a [commit](https://github.com/Philippe-Cholet/checkio-mission-find-rectangles/commit/d7474d82501bd4e85bed1434577d6e2350131371) for that: task description with SVG and PNG images updated.

**Comment by Philippe-Cholet** [comment]
We do not see the difference on checkio task description yet, there is a sync issue since a few days. It will be synced but when, that I do not know.

**Comment by Philippe-Cholet** [comment]
Synced, you can see changes on CheckiO.

**Comment by nmay231** [comment]
Awesome! :+1:

**Pull request closed without merging**
